--2A
CREATE OR REPLACE VIEW DOIS_A AS
SELECT AUTOESTRADA2 AS LIGACAO_COM_A4, kmAE2 AS KM
FROM NOS
WHERE AUTOESTRADA1 Like ('A4')
UNION
SELECT AUTOESTRADA1 AS LIGACAO_COM_A4, kmAE1 AS KM
FROM NOS
WHERE AUTOESTRADA2 Like ('A4');

--2B
CREATE OR REPLACE VIEW DOIS_B AS
SELECT AUTOESTRADAcodigoAutoestrada AS AUTOESTRADA, cod_portico AS PORTICOS
FROM PORTICO
MINUS
SELECT PORTICOAUTOESTRADAcodigoAutoestrada AS AUTOESTRADA, Porticocod_portico AS PORTICOS
FROM PASSAGEM
WHERE PASSAGEM.VEICULOMATRICULA IN (SELECT VEICULO.MATRICULA FROM VEICULO WHERE CLASSEcodigo_classe LIKE 'CLA4');

--2C
CREATE OR REPLACE VIEW DOIS_C AS
SELECT IDENTIFICADORNUMEROSERIE AS IDENTIFICADOR, MATRICULA AS MATRICULA 
FROM VEICULO
WHERE IDENTIFICADORNUMEROSERIE IN (
    SELECT IDENTIFICADORnumeroSerie
    FROM VIAGEM
    WHERE IDENTIFICADORnumeroSerie IS NOT NULL 
    HAVING COUNT(DISTINCT codigoAutoestrada_e) >= (SELECT COUNT ( DISTINCT AUTOESTRADAcodigoAutoestrada) FROM PORTAGEM)
    GROUP BY IDENTIFICADORnumeroSerie);
    
--2D
CREATE OR REPLACE VIEW DOIS_D AS
SELECT CLI.NIF
FROM CLIENTES CLI, VEICULO VEI
WHERE CLI.COD_CLIENTE = VEI.CLIENTECODCLIENTE AND VEI.IDENTIFICADORNUMEROSERIE IN (
    SELECT IDENTIFICADORNUMEROSERIE
    FROM PASSAGEM
    WHERE DATAPASSAGEM BETWEEN '2016-01-01 00:00:01' AND '2016-12-31 23:59:59'
    MINUS
    SELECT IDENTIFICADORNUMEROSERIE
    FROM VIAGEM
    WHERE DIAHORA_E BETWEEN '2016-01-01 00:00:01' AND '2016-12-31 23:59:59')
GROUP BY CLI.NIF;

--2E
CREATE OR REPLACE VIEW DOIS_E AS
SELECT DISTINCT IDENTIFICADORNUMEROSERIE AS IDENTIFICADOR
FROM VIAGEM
WHERE   IDENTIFICADORNUMEROSERIE IS NOT NULL AND
        DIAHORA_E BETWEEN '2017-01-01 00:00:01' AND '2017-12-31 23:59:59'
UNION
SELECT DISTINCT VIA.IDENTIFICADORNUMEROSERIE AS IDENTIFICADOR
FROM VIAGEM VIA
    JOIN PORTAGEM POR ON VIA.PORTAGEMCOD_PORTAGEM_E = POR.COD_PORTAGEM 
    AND VIA.CODIGOAUTOESTRADA_E = POR.AUTOESTRADACODIGOAUTOESTRADA
    JOIN PORTAGEM POR2 ON VIA.PORTAGEMCOD_PORTAGEM_S = POR2.COD_PORTAGEM 
    AND VIA.CODIGOAUTOESTRADA_S = POR2.AUTOESTRADACODIGOAUTOESTRADA
WHERE   VIA.IDENTIFICADORNUMEROSERIE IS NOT NULL AND
        VIA.DIAHORA_E BETWEEN '2017-01-01 00:00:01' AND '2017-12-31 23:59:59'
        AND ABS(POR.KMAUTOESTRADA - POR2.KMAUTOESTRADA) > 20;

--2F 
CREATE OR REPLACE VIEW DOIS_F AS
SELECT VEI.IDENTIFICADORNUMEROSERIE AS IDENTIFICADOR, VEI.MATRICULA AS MATRICULA
FROM VEICULO VEI
    JOIN PASSAGEM PASS ON VEI.IDENTIFICADORNUMEROSERIE = PASS.IDENTIFICADORNUMEROSERIE
WHERE   VEI.CLASSECODIGO_CLASSE LIKE 'CLA1' AND
        PASS.DATAPASSAGEM BETWEEN '2016-01-01 00:00:01' AND '2016-12-31 23:59:59' AND
        PASS.TAXA_PORTICOSCOD_PORTICO > 2
GROUP BY VEI.IDENTIFICADORNUMEROSERIE, VEI.MATRICULA;
    
--2G
CREATE OR REPLACE VIEW DOIS_G AS
SELECT CODIGOAUTOESTRADA_E AS AUTOESTRADA
FROM VIAGEM
WHERE DIAHORA_E BETWEEN '2017-01-01 00:00:01' AND '2017-10-10 23:59:59' AND 
    IDENTIFICADORNUMEROSERIE IN
    (SELECT NUMEROSERIE
    FROM IDENTIFICADOR
    WHERE ESTADO_IDENTIFICADOR = 0) 
HAVING COUNT(CODIGOAUTOESTRADA_E) > 
                (SELECT COUNT (PORTICOAUTOESTRADACODIGOAUTOESTRADA) AS PASSAGENS
                FROM PASSAGEM
                WHERE DATAPASSAGEM BETWEEN '2017-01-01 00:00:01' AND '2017-10-10 23:59:59' AND
                    IDENTIFICADORNUMEROSERIE IN
                                            (SELECT NUMEROSERIE
                                            FROM IDENTIFICADOR
                                            WHERE ESTADO_IDENTIFICADOR = 0)
                GROUP BY PORTICOAUTOESTRADACODIGOAUTOESTRADA)
GROUP BY CODIGOAUTOESTRADA_E
ORDER BY COUNT(CODIGOAUTOESTRADA_E) DESC;
